import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProviderContext } from "../utils/themeContext.jsx";
import AppHeader from "../components/AppHeader/index.jsx";
import FooterComponent from "@/components/FooterComponent";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Arya Labs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <ThemeProviderContext>
          <AppHeader />
          {children}
          <FooterComponent />
        </ThemeProviderContext>
      </body>
    </html>
  );
}
